utils: Build with older compilers that do not default to C99 or newer
Fix building with older compilers that do not default to C99 or newer,
resulting in errors like the following:

-----------------------------------------------------------------------
In file included from ../bind-mount.c:24:0:
../utils.h: In function ‘cleanup_fdsetp’:
../utils.h:260:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (size_t i = 0; i < set->len; i++)
-----------------------------------------------------------------------

This was the only occurrence of initial declarations in for loops, so
the change also realigns the code style to what is used for the rest of
the project.

Signed-off-by: Antonio Ospite <antonio.ospite@collabora.com>