die_with_error: Save errno sooner
We need to save errno immediately, otherwise it could be overwritten
by a failing library call somewhere in the implementation of fprintf.

Signed-off-by: Simon McVittie <smcv@collabora.com>